#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GSLX680)	+= rockchip_gslX680.o
obj-y += ../../../../drivers/input/touchscreen/gslx680/gsl_point_id


